# azure-pipelines.yml
# Enfocado en PUBLICAR artefactos: frontend_dist y backend_build
trigger: none   # por ahora lo corrés manualmente

pool:
  name: TP4_PipelineADO   # <-- tu pool self-hosted

stages:
- stage: CI
  displayName: "CI - Build & Artifacts"
  jobs:
  - job: frontend
    displayName: "Frontend: build & publish"
    steps:
    - checkout: self

    - powershell: |
        npm ci
        npm run build
      workingDirectory: frontend
      displayName: "Build frontend (Vite)"

    - publish: frontend/dist
      artifact: frontend_dist
      displayName: "Publicar artefacto: frontend_dist"

  - job: backend
    displayName: "Backend: build & publish"
    steps:
    - checkout: self

    - powershell: |
        npm ci
        npm run build
      workingDirectory: backend
      displayName: "Build backend"

    - publish: backend/build
      artifact: backend_build
      displayName: "Publicar artefacto: backend_build"
