# azure-pipelines.yml
# Hola Mundo: verifica que el agente self-hosted ejecuta un job básico
trigger: none  # lo corrés manualmente desde "Run pipeline"

pool:
  name: TP4_PipelineADO   # tu pool self-hosted

stages:
- stage: CI
  displayName: "CI - Hola Mundo"
  jobs:
  - job: hello
    displayName: "Job: saludo y entorno"
    steps:
    - checkout: self
      displayName: "Checkout repo"

    - powershell: |
        Write-Host "✅ Hola desde el agente self-hosted!"
        Write-Host "Máquina: $env:COMPUTERNAME"
        Write-Host "Usuario del servicio: $(whoami)"
        Write-Host "Ruta actual: $(Get-Location)"
      displayName: "Echo de entorno (PowerShell)"

    - powershell: |
        $hasNode = (Get-Command node -ErrorAction SilentlyContinue) -ne $null
        if ($hasNode) { node -v } else { Write-Host "Node no encontrado (ok para esta prueba)" }
        $hasDotnet = (Get-Command dotnet -ErrorAction SilentlyContinue) -ne $null
        if ($hasDotnet) { dotnet --version } else { Write-Host ".NET SDK no encontrado (ok para esta prueba)" }
      displayName: "Chequear toolchains (opcional)"

    - powershell: |
        New-Item -ItemType Directory -Force -Path out | Out-Null
        "Hola mundo desde ADO en $(Get-Date -Format o)" | Out-File -FilePath out/saludo.txt -Encoding utf8
      displayName: "Generar artefacto de prueba"

    - publish: out
      artifact: hola_mundo
      displayName: "Publicar artefacto: hola_mundo"
